---
title: "Clinical Registry Reporting"
subtitle: "using R"  
author: 
  - "Farhad Salimis"
institute: "Clinical Outcomes Data Reporting and Research Program (CORRP)"
date: "13 April 2022"
params:
  whyR: TRUE
  workflow: TRUE
  import: TRUE
  tidydata: FALSE
  communicate: TRUE
  reproducible: TRUE
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      # slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

```{r child = "1_whyR.Rmd", eval = params$whyR}

```

---

```{r child = "2_workflow.Rmd", eval = params$workflow}

```


---

```{r child = "3_import.Rmd", eval = params$import}

```


---

```{r child = "4_tidydata.Rmd", eval = params$tidydata}

```


```{r child = "5_communicate.Rmd", eval = params$communicate}

```

---
```{r child = "6_reproducible.Rmd", eval = params$reproducible}

```

---
class: center, middle

# Thanks!

Slides were created via the R packages:

[**xaringan**](https://github.com/yihui/xaringan)<br>
[gadenbuie/xaringanthemer](https://github.com/gadenbuie/xaringanthemer)

**No PowerPoint or Keynote was harmed during the making of these slides!!**
